# Action setup

name: setup pnpm and node.js for CI/CD
description: This action sets up pnpm and node.js for CI/CD workflows.

inputs: 
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '24'

  pnpm-version:
    description: 'pnpm version'
    required: true
    default: '11'

runs: 
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
        install: false