# Events

name: Test 04 - Events

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  issue:
    runs-on: ubuntu-24.04
    # Permisos para que el bot pueda realizar alguna acción, por ejemplo, comentar en la issue.
    permissions:
      issues: write
    steps:
      - name: Inspeccionar eventos
        run: |
          echo "Evento: ${{ github.event_name }}"
          echo "Acción: ${{ github.event.action }}"
          echo "Comentario: ${{ github.event.comment.body }}"
          echo "Número de issue: ${{ github.event.issue.number }}"
          echo "Título de issue: ${{ github.event.issue.title }}"
          echo "Cuerpo de issue: ${{ github.event.issue.body }}"
          echo "Usuario que abrió la issue: ${{ github.event.issue.user.login }}"

      - name: Comentar como bot en GitHub Actions
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: gh issue comment $ISSUE_NUMBER --repo $GITHUB_REPOSITORY --body "Gracias por abrir la issue. Estamos revisando tu solicitud."
      - name: Comentar como autor en Issues con GH Actions
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          GH_ACCESS_TOKEN: ${{ secrets.PERSONAL_ISSUES_ACCESS_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: GH_TOKEN="$GH_ACCESS_TOKEN" gh issue comment $ISSUE_NUMBER --repo $GITHUB_REPOSITORY --body "Gracias por abrir la issue. Estamos revisando la solicitud"
