# Notas
# Las tabulaciones son importantes en los archivos YML.

name: Test - Flow

# En que lugar debe funcionar
on:
  push:
    # Los branches donde trabaja cuando se haga un push
    branches: [main, develop]

# Los trabajos que tiene que realizar
jobs:
  # Nombre que queramos para el trabajo
  hello-exampe:
    # Utilizar siempre latest esta mal
    runs-on: ubuntu-24.04
    # Los pasos que debe realizar este trabajo
    steps:
      - name: Saludar
        run: echo "Hola desde GitHub Actions"

      - name: Ver fecha del runner
        run: date

      - name: Archivos del proyecto
        run: ls -la

      - name: Decir adios
        run: echo "Adios"
